"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Module(google.protobuf.message.Message):
    """Module is the config object of the bank module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BLOCKED_MODULE_ACCOUNTS_OVERRIDE_FIELD_NUMBER: builtins.int
    AUTHORITY_FIELD_NUMBER: builtins.int
    @property
    def blocked_module_accounts_override(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """blocked_module_accounts configures exceptional module accounts which should be blocked from receiving funds.
        If left empty it defaults to the list of account names supplied in the auth module configuration as
        module_account_permissions
        """
    authority: builtins.str
    """authority defines the custom module authority. If not set, defaults to the governance module."""
    def __init__(
        self,
        *,
        blocked_module_accounts_override: collections.abc.Iterable[builtins.str] | None = ...,
        authority: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["authority", b"authority", "blocked_module_accounts_override", b"blocked_module_accounts_override"]) -> None: ...

global___Module = Module
