# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nibiru/inflation/v1/inflation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#nibiru/inflation/v1/inflation.proto\x12\x13nibiru.inflation.v1\x1a\x14gogoproto/gogo.proto\"\xa6\x02\n\x15InflationDistribution\x12W\n\x0fstaking_rewards\x18\x01 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\x0estakingRewards\x12U\n\x0e\x63ommunity_pool\x18\x02 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\rcommunityPool\x12]\n\x12strategic_reserves\x18\x03 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\x11strategicReserves\"\xd2\x01\n\x16\x45xponentialCalculation\x12<\n\x01\x61\x18\x01 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\x01\x61\x12<\n\x01r\x18\x02 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\x01r\x12<\n\x01\x63\x18\x03 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\x01\x63\x42\x31Z/github.com/NibiruChain/nibiru/x/inflation/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nibiru.inflation.v1.inflation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/NibiruChain/nibiru/x/inflation/types'
  _INFLATIONDISTRIBUTION.fields_by_name['staking_rewards']._options = None
  _INFLATIONDISTRIBUTION.fields_by_name['staking_rewards']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _INFLATIONDISTRIBUTION.fields_by_name['community_pool']._options = None
  _INFLATIONDISTRIBUTION.fields_by_name['community_pool']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _INFLATIONDISTRIBUTION.fields_by_name['strategic_reserves']._options = None
  _INFLATIONDISTRIBUTION.fields_by_name['strategic_reserves']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _EXPONENTIALCALCULATION.fields_by_name['a']._options = None
  _EXPONENTIALCALCULATION.fields_by_name['a']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _EXPONENTIALCALCULATION.fields_by_name['r']._options = None
  _EXPONENTIALCALCULATION.fields_by_name['r']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _EXPONENTIALCALCULATION.fields_by_name['c']._options = None
  _EXPONENTIALCALCULATION.fields_by_name['c']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _INFLATIONDISTRIBUTION._serialized_start=83
  _INFLATIONDISTRIBUTION._serialized_end=377
  _EXPONENTIALCALCULATION._serialized_start=380
  _EXPONENTIALCALCULATION._serialized_end=590
# @@protoc_insertion_point(module_scope)
