"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class EventEpochStart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EPOCH_NUMBER_FIELD_NUMBER: builtins.int
    EPOCH_START_TIME_FIELD_NUMBER: builtins.int
    epoch_number: builtins.int
    """Epoch number, starting from 1."""
    @property
    def epoch_start_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The start timestamp of the epoch."""
    def __init__(
        self,
        *,
        epoch_number: builtins.int = ...,
        epoch_start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["epoch_start_time", b"epoch_start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["epoch_number", b"epoch_number", "epoch_start_time", b"epoch_start_time"]) -> None: ...

global___EventEpochStart = EventEpochStart

@typing_extensions.final
class EventEpochEnd(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EPOCH_NUMBER_FIELD_NUMBER: builtins.int
    epoch_number: builtins.int
    """Epoch number, starting from 1."""
    def __init__(
        self,
        *,
        epoch_number: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["epoch_number", b"epoch_number"]) -> None: ...

global___EventEpochEnd = EventEpochEnd
