# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosmos/base/store/v1beta1/listening.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tendermint.abci import types_pb2 as tendermint_dot_abci_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)cosmos/base/store/v1beta1/listening.proto\x12\x19\x63osmos.base.store.v1beta1\x1a\x1btendermint/abci/types.proto\"j\n\x0bStoreKVPair\x12\x1b\n\tstore_key\x18\x01 \x01(\tR\x08storeKey\x12\x16\n\x06\x64\x65lete\x18\x02 \x01(\x08R\x06\x64\x65lete\x12\x10\n\x03key\x18\x03 \x01(\x0cR\x03key\x12\x14\n\x05value\x18\x04 \x01(\x0cR\x05value\"\x83\x05\n\rBlockMetadata\x12R\n\x13request_begin_block\x18\x01 \x01(\x0b\x32\".tendermint.abci.RequestBeginBlockR\x11requestBeginBlock\x12U\n\x14response_begin_block\x18\x02 \x01(\x0b\x32#.tendermint.abci.ResponseBeginBlockR\x12responseBeginBlock\x12S\n\x0b\x64\x65liver_txs\x18\x03 \x03(\x0b\x32\x32.cosmos.base.store.v1beta1.BlockMetadata.DeliverTxR\ndeliverTxs\x12L\n\x11request_end_block\x18\x04 \x01(\x0b\x32 .tendermint.abci.RequestEndBlockR\x0frequestEndBlock\x12O\n\x12response_end_block\x18\x05 \x01(\x0b\x32!.tendermint.abci.ResponseEndBlockR\x10responseEndBlock\x12H\n\x0fresponse_commit\x18\x06 \x01(\x0b\x32\x1f.tendermint.abci.ResponseCommitR\x0eresponseCommit\x1a\x88\x01\n\tDeliverTx\x12;\n\x07request\x18\x01 \x01(\x0b\x32!.tendermint.abci.RequestDeliverTxR\x07request\x12>\n\x08response\x18\x02 \x01(\x0b\x32\".tendermint.abci.ResponseDeliverTxR\x08responseB*Z(github.com/cosmos/cosmos-sdk/store/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.base.store.v1beta1.listening_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(github.com/cosmos/cosmos-sdk/store/types'
  _STOREKVPAIR._serialized_start=101
  _STOREKVPAIR._serialized_end=207
  _BLOCKMETADATA._serialized_start=210
  _BLOCKMETADATA._serialized_end=853
  _BLOCKMETADATA_DELIVERTX._serialized_start=717
  _BLOCKMETADATA_DELIVERTX._serialized_end=853
# @@protoc_insertion_point(module_scope)
