# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nibiru/stablecoin/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!nibiru/stablecoin/v1/events.proto\x12\x14nibiru.stablecoin.v1\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"h\n\rEventTransfer\x12\x33\n\x04\x63oin\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x04\x63oin\x12\x12\n\x04\x66rom\x18\x02 \x01(\tR\x04\x66rom\x12\x0e\n\x02to\x18\x03 \x01(\tR\x02to\"Y\n\x0f\x45ventMintStable\x12\x46\n\x06\x61mount\x18\x01 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.IntR\x06\x61mount\"Y\n\x0f\x45ventBurnStable\x12\x46\n\x06\x61mount\x18\x01 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.IntR\x06\x61mount\"W\n\rEventMintNIBI\x12\x46\n\x06\x61mount\x18\x01 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.IntR\x06\x61mount\"W\n\rEventBurnNIBI\x12\x46\n\x06\x61mount\x18\x01 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.IntR\x06\x61mount\"\xf3\x01\n\x14\x45ventRecollateralize\x12\x16\n\x06\x63\x61ller\x18\x01 \x01(\tR\x06\x63\x61ller\x12\x38\n\x07in_coin\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x06inCoin\x12:\n\x08out_coin\x18\x03 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x07outCoin\x12M\n\ncoll_ratio\x18\x04 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\tcollRatio\"\xeb\x01\n\x0c\x45ventBuyback\x12\x16\n\x06\x63\x61ller\x18\x01 \x01(\tR\x06\x63\x61ller\x12\x38\n\x07in_coin\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x06inCoin\x12:\n\x08out_coin\x18\x03 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x07outCoin\x12M\n\ncoll_ratio\x18\x04 \x01(\tB.\xc8\xde\x1f\x00\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.DecR\tcollRatioB2Z0github.com/NibiruChain/nibiru/x/stablecoin/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nibiru.stablecoin.v1.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/NibiruChain/nibiru/x/stablecoin/types'
  _EVENTTRANSFER.fields_by_name['coin']._options = None
  _EVENTTRANSFER.fields_by_name['coin']._serialized_options = b'\310\336\037\000'
  _EVENTMINTSTABLE.fields_by_name['amount']._options = None
  _EVENTMINTSTABLE.fields_by_name['amount']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int'
  _EVENTBURNSTABLE.fields_by_name['amount']._options = None
  _EVENTBURNSTABLE.fields_by_name['amount']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int'
  _EVENTMINTNIBI.fields_by_name['amount']._options = None
  _EVENTMINTNIBI.fields_by_name['amount']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int'
  _EVENTBURNNIBI.fields_by_name['amount']._options = None
  _EVENTBURNNIBI.fields_by_name['amount']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Int'
  _EVENTRECOLLATERALIZE.fields_by_name['in_coin']._options = None
  _EVENTRECOLLATERALIZE.fields_by_name['in_coin']._serialized_options = b'\310\336\037\000'
  _EVENTRECOLLATERALIZE.fields_by_name['out_coin']._options = None
  _EVENTRECOLLATERALIZE.fields_by_name['out_coin']._serialized_options = b'\310\336\037\000'
  _EVENTRECOLLATERALIZE.fields_by_name['coll_ratio']._options = None
  _EVENTRECOLLATERALIZE.fields_by_name['coll_ratio']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _EVENTBUYBACK.fields_by_name['in_coin']._options = None
  _EVENTBUYBACK.fields_by_name['in_coin']._serialized_options = b'\310\336\037\000'
  _EVENTBUYBACK.fields_by_name['out_coin']._options = None
  _EVENTBUYBACK.fields_by_name['out_coin']._serialized_options = b'\310\336\037\000'
  _EVENTBUYBACK.fields_by_name['coll_ratio']._options = None
  _EVENTBUYBACK.fields_by_name['coll_ratio']._serialized_options = b'\310\336\037\000\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec'
  _EVENTTRANSFER._serialized_start=113
  _EVENTTRANSFER._serialized_end=217
  _EVENTMINTSTABLE._serialized_start=219
  _EVENTMINTSTABLE._serialized_end=308
  _EVENTBURNSTABLE._serialized_start=310
  _EVENTBURNSTABLE._serialized_end=399
  _EVENTMINTNIBI._serialized_start=401
  _EVENTMINTNIBI._serialized_end=488
  _EVENTBURNNIBI._serialized_start=490
  _EVENTBURNNIBI._serialized_end=577
  _EVENTRECOLLATERALIZE._serialized_start=580
  _EVENTRECOLLATERALIZE._serialized_end=823
  _EVENTBUYBACK._serialized_start=826
  _EVENTBUYBACK._serialized_end=1061
# @@protoc_insertion_point(module_scope)
